EPPlus.WebSampleMvc.NetCore/Controllers/BlazorSamplesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EPPlus.WebSampleMvc.NetCore.Controllers
{
    public class BlazorSamplesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sample1()
        {
            return View();
        }

        [HttpGet, Route("/api/fxrates")]
        public IActionResult FxRates()
        {
            var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"data\\FxRates.json");
            var json = System.IO.File.ReadAllText(path);
            return Json(json);
        }
    }
}

EPPlus.WebSampleMvc.NetCore/Controllers/HtmlExportController.cs
using EPPlus.WebSampleMvc.NetCore.Models.HtmlExport;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EPPlus.WebSampleMvc.NetCore.Controllers
{
    public class HtmlExportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private const string ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

        [HttpGet]
        public IActionResult ExportTable1()
        {
            var model = new ExportTable1Model();
            model.SetupSampleData(0);
            model.TableStyle = "Dark1";
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult ExportTable1(ExportTable1Model model)
        {
            if(!Enum.TryParse(model.TableStyle, out TableStyles ts))
            {
                ts = TableStyles.Light1;
            }
            ViewData["TableStyle"] = ts.ToString();
            model.SetupSampleData(model.Theme, ts);
            if(model.GetWorkbook)
            {
                return File(model.WorkbookBytes, ContentType, "EPPlusHtmlSample1.xlsx");
            }
            return View(model);
        }

        public IActionResult ExportTable2(string style)
        {
            if (!Enum.TryParse(style, out TableStyles ts))
            {
                ts = TableStyles.Dark1;
            }
            ViewData["TableStyle"] = ts.ToString();
            var model = new ExportTable2Model();
            model.SetupSampleData(ts);
            return View(model);
        }

        public IActionResult ExportTable3(string style)
        {
            if (!Enum.TryParse(style, out TableStyles ts))
            {
                ts = TableStyles.Light2;
            }
            var model = new ExportTable3Model();
            model.SetupSampleData(ts);
            return View(model);
        }

        public IActionResult ExportTable4(string style)
        {
            if (!Enum.TryParse(style, out TableStyles ts))
            {
                ts = TableStyles.Light2;
            }
            var model = new ExportTable4Model();
            model.SetupSampleData(ts);
            return View(model);
        }

        public IActionResult ExportRange5()
        {
            var model = new ExportRange5Model();
            model.SetupSampleData();
            return View(model);
        }

        public IActionResult ExportRanges6()
        {
            var model = new ExportRanges6Model();
            model.SetupSampleData();
            return View(model);
        }

        [HttpGet]
        public IActionResult ExportCf7()
        {
            var model = new ExportCf7Model();
            model.SetupSampleData();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult ExportCf7(string tn)
        {
            var model = new ExportCf7Model();
            model.SelectedSample = tn;
            model.SetupSampleData(tn);
            return View(model);
        }

        public async Task<IActionResult> GetWorkbookSample5()
        {
            var file = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"data\\Allsvenskan2001.xlsx");
            using var package = new ExcelPackage(file);
            var fileBytes = await package.GetAsByteArrayAsync();
            return File(fileBytes, ContentType, "EPPlusHtmlSample5.xlsx");
        }

        public async Task<IActionResult> GetWorkbookSample6()
        {
            var file = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"data\\SwedishGeography.xlsx");
            using var package = new ExcelPackage(file);
            var fileBytes = await package.GetAsByteArrayAsync();
            return File(fileBytes, ContentType, "EPPlusHtmlSample6.xlsx");
        }

        public async Task<IActionResult> GetWorkbookSample7()
        {
            var file = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"data\\CfExport1.xlsx");
            using var package = new ExcelPackage(file);
            var fileBytes = await package.GetAsByteArrayAsync();
            return File(fileBytes, ContentType, "EPPlusHtmlSample7.xlsx");
        }
    }
}

EPPlus.WebSampleMvc.NetCore/Controllers/JsonExportController.cs
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;

namespace EPPlus.WebSampleMvc.NetCore.Controllers
{
    public class JsonExportController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sample1()
        {
            return View();
        }

        [HttpGet, Route("/api/currencyrates")]
        public async Task<JsonResult> Sample1GetJsonData()
        {
            using(var package = new ExcelPackage())
            {
                var sheet = package.Workbook.Worksheets.Add("Currencies");
                var csvFileInfo = new FileInfo(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"data\\currencies2011weekly.csv"));
                var format = new ExcelTextFormat
                {
                    Delimiter = ';',
                    Culture = CultureInfo.InvariantCulture,
                    DataTypes = new eDataTypes[] { eDataTypes.DateTime, eDataTypes.Number, eDataTypes.Number, eDataTypes.Number, eDataTypes.Number }                    
                };
                var range = await sheet.Cells["A1"].LoadFromTextAsync(csvFileInfo, format);
                sheet.Cells[range.Start.Row, 1, range.End.Row, 1].Style.Numberformat.Format = "yyyy-MM-dd";
                sheet.Cells[range.Start.Row, 2, range.End.Row, 5].Style.Numberformat.Format = "#,##0.0000";
                var jsonData = range.ToJson(x=>x.AddDataTypesOn = eDataTypeOn.OnColumn);
                return Json(jsonData);
            }
        }
    }
}

EPPlus.WebSampleMvc.NetCore/Controllers/SamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using OfficeOpenXml;

namespace EPPlus.WebSampleMvc.NetCore.Controllers
{
    public class SamplesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private const string ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

        /// <summary>
        /// Simple example on how to create a workbook without
        /// access to the file system and return it as a file.
        /// </summary>
        /// <returns>A workbook as a file with filename and content type set</returns>
        [HttpGet]
        public IActionResult WebSample1()
        {
            using(var package = new ExcelPackage())
            {
                var sheet = package.Workbook.Worksheets.Add("Sheet 1");
                sheet.Cells["A1:C1"].Merge = true;
                sheet.Cells["A1"].Style.Font.Size = 18f;
                sheet.Cells["A1"].Style.Font.Bold = true;
                sheet.Cells["A1"].Value = "Simple example 1";
                var excelData = package.GetAsByteArray();
                var fileName = "MyWorkbook.xlsx";
                return File(excelData, ContentType, fileName);
            }
        }
    }
}

EPPlus.WebSampleMvc.NetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EPPlus.WebSampleMvc.NetCore</title>
    <base href="/" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/EPPlus-logo-full.png" style="width:204px;height:38px" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Samples" asp-action="Index">Samples</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HtmlExport" asp-action="Index">Html export</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JsonExport" asp-action="Index">JSON export</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BlazorSamples" asp-action="Index">Blazor samples</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EPPlus.WebSampleMvc.NetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.21/datatables.min.js"></script>
</body>
</html>